config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  
  resources :users, only: [:show] do
    resources :posts, only: [:index, :show, :destroy]
  end

  resources :posts, only: [:new, :create] do
    resources :comments, only: [:new, :create, :destroy]
    resources :likes, only: [:create]
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is? :admin
      can :destroy, [Post, Comment]
    else
      can :destroy, [Post, Comment],
          author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comment_counter
  after_destroy :reduce_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end

  def reduce_comment_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comment, dependent: :destroy
  has_many :like, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  after_destroy :reduce_posts_counter

  def best_five_comments
    comment.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def reduce_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :post, foreign_key: 'author_id'
  has_many :like, foreign_key: 'author_id'
  has_many :comment, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def best_three_posts
    post.order(created_at: :desc).limit(3)
  end

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    post = Post.find(params[:post_id])
    @comment = post.comment.new(author: current_user, **comment_param)
    if @comment.save
      redirect_to user_post_path(post.author, post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.destroy
        format.html do
          redirect_to user_post_path(current_user, Post.find(params[:post_id])),
                      notice: 'Comment was successfully deleted.'
        end
      end
    end
  end

  private

  def comment_param
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @like = post.like.new(author: current_user)
    puts 'Queen'
    if @like.save
      puts post.id
      redirect_to user_post_path(post.author, post)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:post, :comment).find(params[:user_id])
    @posts = Post.includes(:comment, :author).where(author_id: @user.id)
  end

  def show
    @post = Post.where(author_id: params[:user_id], id: params[:id]).first
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.post.new(post_param)
    if @post.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.destroy
        format.html { redirect_to user_posts_path(current_user), notice: 'Post was successfully deleted.' }
      end
    end
  end

  private

  def post_param
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:post).all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model:([@post, @comment]), html: { class: 'form-c'} do |form|%>
<%=form.label "Enter Comment", class: 'field-label-c'%>
<%=form.text_area :text, class: 'field-c'%>
<%=form.submit "Comment", class: 'form-btn'%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/linked/_comment.html.erb
<ul class='comment-content'>
<% comments.each do |comment|%>
<li><%= comment.author.name%>: <%=comment.text%>
    <% if can? :destroy, comment %>
    <%=button_to "delete", post_comment_path(post, comment), method: :delete, class: ['add-comment-btn'] %> 
    <% end %>
</li>
<%end%>
<%= 'No comments' if comments.empty?%>
</ul>

app/views/linked/_comment_form.html.erb
<%= form_with model:([post, comments]), html: { class: 'form-c'} do |form|%>
<%=form.label "Enter Comment", class: 'field-label-c'%>
<%=form.text_area :text, class: 'field-c'%>
<%=form.submit "Comment", class: 'form-btn'%>
<%end%>

app/views/linked/_post.html.erb
<%=link_to user_post_path(post.author, post), class:'post-content', id:post.title do%>
<h3><%=post.title%></h3>
<div><%=post.text[0, 100]%><%='...' if post.text[51]%></div>
<div class='post-total'>Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%></div>
<%end%>

app/views/linked/_user.html.erb
 <div class='user-content'>
 <%= image_tag user.photo ? user.photo : '', alt: "#{user.name} profile image", class: 'profile'%>
 <%= link_to user,class:'user-content-details', id:user.id do
 %>
 <h2><%= user.name %></h2>
 <div class='user-post-total'>Number of posts: <%=user.posts_counter%> </div>
 <%end%>
 </div>

app/views/posts/index.html.erb
<%= render 'linked/user', user: @user%>
<ul>
<% if @user.post.empty? %>
  <p class='no-posts'>No posts</p>
<% else %>
<% @user.post.each do |post|%>
<li>
  <%= render 'linked/post', post: post %>
  <%= render 'linked/comment', comments: post.best_five_comments%>
</li>
<%end%>
<%end%>
</ul>
<div class="pagination"></div>

app/views/posts/new.html.erb
<%= form_with model:@post, html: { class: 'form-p'} do |form|%>
<h1>Create Post</h1>
<%=form.label :title%>
<%=form.text_field :title, class: 'text-field-p'%>
<%=form.label "Post"%>
<%=form.text_area :text, class: 'text-area-p'%>
<%=form.submit "Post", class: 'form-btn'%>
<%end%>

app/views/posts/show.html.erb
<article class='no-posts'>
  <div class='post-title' >
  <h1><%=@post.title%> by <%=@post.author.name%><h1>
  <div class='post-count-best'>Comments: <%=@post.comments_counter%>, Likes:<%=@post.likes_counter%></div>
  </div>
  <div><%=@post.text%></div>
  <%=button_to "Like", post_likes_path(@post), method: :post, class: ['form-btn, rid-btn']%>
  <%= render 'linked/comment', post: @post, comments: @post.best_five_comments%>
  <%=link_to 'Add comment', new_post_comment_path(@post), class: ['add-comment-btn']%>

  <% if can? :destroy, @post %>
    <%=button_to "delete", user_post_path(@post.author, @post), method: :delete, class: ['add-comment-btn'] %> 
  <% end %>
</article>

app/views/users/index.html.erb
<h1 class='intro'>Powered By Ruby On Rails <%=@current_user && @current_user.name%></h1>
<div class='post-btn'><%= link_to "Create Post", new_post_path, class: 'create-post-btn' %></div>
<ul>
<% @users.each do |user|%>
<li>
  <%= render 'linked/user', user: user%>
</li>
<% end %>
</ul>

app/views/users/show.html.erb
<%= render 'linked/user', user: @user%>
<div class='bio'><%=@user.bio%></div>
<ul class='user-post-list'>
<%if @user.best_three_posts.empty?%>
<p class='no-posts'>No posts</p>
<%else%>
<%@user.best_three_posts.each do |post| %>
<li>
<%=render 'linked/post', post: post%>
</li>
<%end%>
<%end%>
</ul>
<div class='content-view-all-post-btn'>
<%= link_to "View all posts", user_posts_path(@user), class: 'view-all-post-btn' %></div>